# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b61ed966f72ed1f9b17b2951d961428d17355522e41fa1ea2fe8c0ee2116b7c764807e84340bbc97bd62c46fc11e207ee7e51fa7e9ffd04c65d14d45da8ba5a

test:
  secret_key_base: 9c5b23190a897f70fbaaa724b28e5369e1b79ba2a3885e187212759339b85a2acc157b55e0eba1f542136ef8a7b4f5fe97e2c9f6b893b3301dfde2e0368b6b7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
